// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.0
// source: internal/server/proto/service.proto

package proto

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type NodeType int32

const (
	NodeType_OtherType NodeType = 0
	NodeType_Beacon    NodeType = 1
	NodeType_Validator NodeType = 2
	NodeType_Bootnode  NodeType = 3
)

// Enum value maps for NodeType.
var (
	NodeType_name = map[int32]string{
		0: "OtherType",
		1: "Beacon",
		2: "Validator",
		3: "Bootnode",
	}
	NodeType_value = map[string]int32{
		"OtherType": 0,
		"Beacon":    1,
		"Validator": 2,
		"Bootnode":  3,
	}
)

func (x NodeType) Enum() *NodeType {
	p := new(NodeType)
	*p = x
	return p
}

func (x NodeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_server_proto_service_proto_enumTypes[0].Descriptor()
}

func (NodeType) Type() protoreflect.EnumType {
	return &file_internal_server_proto_service_proto_enumTypes[0]
}

func (x NodeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeType.Descriptor instead.
func (NodeType) EnumDescriptor() ([]byte, []int) {
	return file_internal_server_proto_service_proto_rawDescGZIP(), []int{0}
}

type NodeClient int32

const (
	NodeClient_OtherClient NodeClient = 0
	NodeClient_Prysm       NodeClient = 1
	NodeClient_Teku        NodeClient = 2
	NodeClient_Lighthouse  NodeClient = 3
)

// Enum value maps for NodeClient.
var (
	NodeClient_name = map[int32]string{
		0: "OtherClient",
		1: "Prysm",
		2: "Teku",
		3: "Lighthouse",
	}
	NodeClient_value = map[string]int32{
		"OtherClient": 0,
		"Prysm":       1,
		"Teku":        2,
		"Lighthouse":  3,
	}
)

func (x NodeClient) Enum() *NodeClient {
	p := new(NodeClient)
	*p = x
	return p
}

func (x NodeClient) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeClient) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_server_proto_service_proto_enumTypes[1].Descriptor()
}

func (NodeClient) Type() protoreflect.EnumType {
	return &file_internal_server_proto_service_proto_enumTypes[1]
}

func (x NodeClient) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeClient.Descriptor instead.
func (NodeClient) EnumDescriptor() ([]byte, []int) {
	return file_internal_server_proto_service_proto_rawDescGZIP(), []int{1}
}

type NodeDeployRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name       string     `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	NodeClient NodeClient `protobuf:"varint,2,opt,name=nodeClient,proto3,enum=proto.NodeClient" json:"nodeClient,omitempty"`
	Repo       string     `protobuf:"bytes,3,opt,name=repo,proto3" json:"repo,omitempty"`
	Tag        string     `protobuf:"bytes,4,opt,name=tag,proto3" json:"tag,omitempty"`
	// Types that are assignable to NodeType:
	//	*NodeDeployRequest_Beacon_
	//	*NodeDeployRequest_Validator_
	NodeType isNodeDeployRequest_NodeType `protobuf_oneof:"NodeType"`
}

func (x *NodeDeployRequest) Reset() {
	*x = NodeDeployRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_server_proto_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodeDeployRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeDeployRequest) ProtoMessage() {}

func (x *NodeDeployRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_server_proto_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeDeployRequest.ProtoReflect.Descriptor instead.
func (*NodeDeployRequest) Descriptor() ([]byte, []int) {
	return file_internal_server_proto_service_proto_rawDescGZIP(), []int{0}
}

func (x *NodeDeployRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NodeDeployRequest) GetNodeClient() NodeClient {
	if x != nil {
		return x.NodeClient
	}
	return NodeClient_OtherClient
}

func (x *NodeDeployRequest) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

func (x *NodeDeployRequest) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (m *NodeDeployRequest) GetNodeType() isNodeDeployRequest_NodeType {
	if m != nil {
		return m.NodeType
	}
	return nil
}

func (x *NodeDeployRequest) GetBeacon() *NodeDeployRequest_Beacon {
	if x, ok := x.GetNodeType().(*NodeDeployRequest_Beacon_); ok {
		return x.Beacon
	}
	return nil
}

func (x *NodeDeployRequest) GetValidator() *NodeDeployRequest_Validator {
	if x, ok := x.GetNodeType().(*NodeDeployRequest_Validator_); ok {
		return x.Validator
	}
	return nil
}

type isNodeDeployRequest_NodeType interface {
	isNodeDeployRequest_NodeType()
}

type NodeDeployRequest_Beacon_ struct {
	Beacon *NodeDeployRequest_Beacon `protobuf:"bytes,20,opt,name=beacon,proto3,oneof"`
}

type NodeDeployRequest_Validator_ struct {
	Validator *NodeDeployRequest_Validator `protobuf:"bytes,21,opt,name=validator,proto3,oneof"`
}

func (*NodeDeployRequest_Beacon_) isNodeDeployRequest_NodeType() {}

func (*NodeDeployRequest_Validator_) isNodeDeployRequest_NodeType() {}

type NodeDeployResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Node *Node `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
}

func (x *NodeDeployResponse) Reset() {
	*x = NodeDeployResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_server_proto_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodeDeployResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeDeployResponse) ProtoMessage() {}

func (x *NodeDeployResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_server_proto_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeDeployResponse.ProtoReflect.Descriptor instead.
func (*NodeDeployResponse) Descriptor() ([]byte, []int) {
	return file_internal_server_proto_service_proto_rawDescGZIP(), []int{1}
}

func (x *NodeDeployResponse) GetNode() *Node {
	if x != nil {
		return x.Node
	}
	return nil
}

type NodeListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NodeListRequest) Reset() {
	*x = NodeListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_server_proto_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodeListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeListRequest) ProtoMessage() {}

func (x *NodeListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_server_proto_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeListRequest.ProtoReflect.Descriptor instead.
func (*NodeListRequest) Descriptor() ([]byte, []int) {
	return file_internal_server_proto_service_proto_rawDescGZIP(), []int{2}
}

type NodeListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Node []*Node `protobuf:"bytes,1,rep,name=node,proto3" json:"node,omitempty"`
}

func (x *NodeListResponse) Reset() {
	*x = NodeListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_server_proto_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodeListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeListResponse) ProtoMessage() {}

func (x *NodeListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_server_proto_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeListResponse.ProtoReflect.Descriptor instead.
func (*NodeListResponse) Descriptor() ([]byte, []int) {
	return file_internal_server_proto_service_proto_rawDescGZIP(), []int{3}
}

func (x *NodeListResponse) GetNode() []*Node {
	if x != nil {
		return x.Node
	}
	return nil
}

type NodeStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *NodeStatusRequest) Reset() {
	*x = NodeStatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_server_proto_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodeStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeStatusRequest) ProtoMessage() {}

func (x *NodeStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_server_proto_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeStatusRequest.ProtoReflect.Descriptor instead.
func (*NodeStatusRequest) Descriptor() ([]byte, []int) {
	return file_internal_server_proto_service_proto_rawDescGZIP(), []int{4}
}

func (x *NodeStatusRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type NodeStatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Node *Node `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
}

func (x *NodeStatusResponse) Reset() {
	*x = NodeStatusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_server_proto_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodeStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeStatusResponse) ProtoMessage() {}

func (x *NodeStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_server_proto_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeStatusResponse.ProtoReflect.Descriptor instead.
func (*NodeStatusResponse) Descriptor() ([]byte, []int) {
	return file_internal_server_proto_service_proto_rawDescGZIP(), []int{5}
}

func (x *NodeStatusResponse) GetNode() *Node {
	if x != nil {
		return x.Node
	}
	return nil
}

type Node struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type   NodeType          `protobuf:"varint,2,opt,name=type,proto3,enum=proto.NodeType" json:"type,omitempty"`
	Client NodeClient        `protobuf:"varint,3,opt,name=client,proto3,enum=proto.NodeClient" json:"client,omitempty"`
	Labels map[string]string `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *Node) Reset() {
	*x = Node{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_server_proto_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_internal_server_proto_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_internal_server_proto_service_proto_rawDescGZIP(), []int{6}
}

func (x *Node) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Node) GetType() NodeType {
	if x != nil {
		return x.Type
	}
	return NodeType_OtherType
}

func (x *Node) GetClient() NodeClient {
	if x != nil {
		return x.Client
	}
	return NodeClient_OtherClient
}

func (x *Node) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type NodeDeployRequest_Beacon struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NodeDeployRequest_Beacon) Reset() {
	*x = NodeDeployRequest_Beacon{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_server_proto_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodeDeployRequest_Beacon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeDeployRequest_Beacon) ProtoMessage() {}

func (x *NodeDeployRequest_Beacon) ProtoReflect() protoreflect.Message {
	mi := &file_internal_server_proto_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeDeployRequest_Beacon.ProtoReflect.Descriptor instead.
func (*NodeDeployRequest_Beacon) Descriptor() ([]byte, []int) {
	return file_internal_server_proto_service_proto_rawDescGZIP(), []int{0, 0}
}

type NodeDeployRequest_Validator struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NumValidators uint64 `protobuf:"varint,1,opt,name=numValidators,proto3" json:"numValidators,omitempty"`
	WithDeposit   bool   `protobuf:"varint,2,opt,name=withDeposit,proto3" json:"withDeposit,omitempty"`
}

func (x *NodeDeployRequest_Validator) Reset() {
	*x = NodeDeployRequest_Validator{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_server_proto_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodeDeployRequest_Validator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeDeployRequest_Validator) ProtoMessage() {}

func (x *NodeDeployRequest_Validator) ProtoReflect() protoreflect.Message {
	mi := &file_internal_server_proto_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeDeployRequest_Validator.ProtoReflect.Descriptor instead.
func (*NodeDeployRequest_Validator) Descriptor() ([]byte, []int) {
	return file_internal_server_proto_service_proto_rawDescGZIP(), []int{0, 1}
}

func (x *NodeDeployRequest_Validator) GetNumValidators() uint64 {
	if x != nil {
		return x.NumValidators
	}
	return 0
}

func (x *NodeDeployRequest_Validator) GetWithDeposit() bool {
	if x != nil {
		return x.WithDeposit
	}
	return false
}

var File_internal_server_proto_service_proto protoreflect.FileDescriptor

var file_internal_server_proto_service_proto_rawDesc = []byte{
	0x0a, 0x23, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xea, 0x02, 0x0a,
	0x11, 0x4e, 0x6f, 0x64, 0x65, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x31, 0x0a, 0x0a, 0x6e, 0x6f, 0x64, 0x65, 0x43, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x0a, 0x6e,
	0x6f, 0x64, 0x65, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x65, 0x70,
	0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x65, 0x70, 0x6f, 0x12, 0x10, 0x0a,
	0x03, 0x74, 0x61, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x74, 0x61, 0x67, 0x12,
	0x39, 0x0a, 0x06, 0x62, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x18, 0x14, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x44, 0x65, 0x70, 0x6c,
	0x6f, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x42, 0x65, 0x61, 0x63, 0x6f, 0x6e,
	0x48, 0x00, 0x52, 0x06, 0x62, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x12, 0x42, 0x0a, 0x09, 0x76, 0x61,
	0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x18, 0x15, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f,
	0x72, 0x48, 0x00, 0x52, 0x09, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x1a, 0x08,
	0x0a, 0x06, 0x42, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x1a, 0x53, 0x0a, 0x09, 0x56, 0x61, 0x6c, 0x69,
	0x64, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x24, 0x0a, 0x0d, 0x6e, 0x75, 0x6d, 0x56, 0x61, 0x6c, 0x69,
	0x64, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0d, 0x6e, 0x75,
	0x6d, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x77,
	0x69, 0x74, 0x68, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x0b, 0x77, 0x69, 0x74, 0x68, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x42, 0x0a, 0x0a,
	0x08, 0x4e, 0x6f, 0x64, 0x65, 0x54, 0x79, 0x70, 0x65, 0x22, 0x35, 0x0a, 0x12, 0x4e, 0x6f, 0x64,
	0x65, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x1f, 0x0a, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x6e, 0x6f, 0x64, 0x65,
	0x22, 0x11, 0x0a, 0x0f, 0x4e, 0x6f, 0x64, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0x33, 0x0a, 0x10, 0x4e, 0x6f, 0x64, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4e, 0x6f,
	0x64, 0x65, 0x52, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x22, 0x27, 0x0a, 0x11, 0x4e, 0x6f, 0x64, 0x65,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x22, 0x35, 0x0a, 0x12, 0x4e, 0x6f, 0x64, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4e, 0x6f,
	0x64, 0x65, 0x52, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x22, 0xd6, 0x01, 0x0a, 0x04, 0x4e, 0x6f, 0x64,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x23, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4e, 0x6f, 0x64, 0x65,
	0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x29, 0x0a, 0x06, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x06, 0x63,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x2f, 0x0a, 0x06, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x18,
	0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4e, 0x6f,
	0x64, 0x65, 0x2e, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x06,
	0x6c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x1a, 0x39, 0x0a, 0x0b, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x73,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38,
	0x01, 0x2a, 0x42, 0x0a, 0x08, 0x4e, 0x6f, 0x64, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0d, 0x0a,
	0x09, 0x4f, 0x74, 0x68, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06,
	0x42, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x56, 0x61, 0x6c, 0x69,
	0x64, 0x61, 0x74, 0x6f, 0x72, 0x10, 0x02, 0x12, 0x0c, 0x0a, 0x08, 0x42, 0x6f, 0x6f, 0x74, 0x6e,
	0x6f, 0x64, 0x65, 0x10, 0x03, 0x2a, 0x42, 0x0a, 0x0a, 0x4e, 0x6f, 0x64, 0x65, 0x43, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x12, 0x0f, 0x0a, 0x0b, 0x4f, 0x74, 0x68, 0x65, 0x72, 0x43, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x50, 0x72, 0x79, 0x73, 0x6d, 0x10, 0x01, 0x12,
	0x08, 0x0a, 0x04, 0x54, 0x65, 0x6b, 0x75, 0x10, 0x02, 0x12, 0x0e, 0x0a, 0x0a, 0x4c, 0x69, 0x67,
	0x68, 0x74, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x10, 0x03, 0x32, 0xcf, 0x01, 0x0a, 0x0a, 0x45, 0x32,
	0x45, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x41, 0x0a, 0x0a, 0x4e, 0x6f, 0x64, 0x65,
	0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x12, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4e,
	0x6f, 0x64, 0x65, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x44, 0x65, 0x70,
	0x6c, 0x6f, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b, 0x0a, 0x08, 0x4e,
	0x6f, 0x64, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x4e, 0x6f, 0x64, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x41, 0x0a, 0x0a, 0x4e, 0x6f, 0x64, 0x65,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4e,
	0x6f, 0x64, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x18, 0x5a, 0x16, 0x2f,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_server_proto_service_proto_rawDescOnce sync.Once
	file_internal_server_proto_service_proto_rawDescData = file_internal_server_proto_service_proto_rawDesc
)

func file_internal_server_proto_service_proto_rawDescGZIP() []byte {
	file_internal_server_proto_service_proto_rawDescOnce.Do(func() {
		file_internal_server_proto_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_server_proto_service_proto_rawDescData)
	})
	return file_internal_server_proto_service_proto_rawDescData
}

var file_internal_server_proto_service_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_internal_server_proto_service_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_internal_server_proto_service_proto_goTypes = []interface{}{
	(NodeType)(0),                       // 0: proto.NodeType
	(NodeClient)(0),                     // 1: proto.NodeClient
	(*NodeDeployRequest)(nil),           // 2: proto.NodeDeployRequest
	(*NodeDeployResponse)(nil),          // 3: proto.NodeDeployResponse
	(*NodeListRequest)(nil),             // 4: proto.NodeListRequest
	(*NodeListResponse)(nil),            // 5: proto.NodeListResponse
	(*NodeStatusRequest)(nil),           // 6: proto.NodeStatusRequest
	(*NodeStatusResponse)(nil),          // 7: proto.NodeStatusResponse
	(*Node)(nil),                        // 8: proto.Node
	(*NodeDeployRequest_Beacon)(nil),    // 9: proto.NodeDeployRequest.Beacon
	(*NodeDeployRequest_Validator)(nil), // 10: proto.NodeDeployRequest.Validator
	nil,                                 // 11: proto.Node.LabelsEntry
}
var file_internal_server_proto_service_proto_depIdxs = []int32{
	1,  // 0: proto.NodeDeployRequest.nodeClient:type_name -> proto.NodeClient
	9,  // 1: proto.NodeDeployRequest.beacon:type_name -> proto.NodeDeployRequest.Beacon
	10, // 2: proto.NodeDeployRequest.validator:type_name -> proto.NodeDeployRequest.Validator
	8,  // 3: proto.NodeDeployResponse.node:type_name -> proto.Node
	8,  // 4: proto.NodeListResponse.node:type_name -> proto.Node
	8,  // 5: proto.NodeStatusResponse.node:type_name -> proto.Node
	0,  // 6: proto.Node.type:type_name -> proto.NodeType
	1,  // 7: proto.Node.client:type_name -> proto.NodeClient
	11, // 8: proto.Node.labels:type_name -> proto.Node.LabelsEntry
	2,  // 9: proto.E2EService.NodeDeploy:input_type -> proto.NodeDeployRequest
	4,  // 10: proto.E2EService.NodeList:input_type -> proto.NodeListRequest
	6,  // 11: proto.E2EService.NodeStatus:input_type -> proto.NodeStatusRequest
	3,  // 12: proto.E2EService.NodeDeploy:output_type -> proto.NodeDeployResponse
	5,  // 13: proto.E2EService.NodeList:output_type -> proto.NodeListResponse
	7,  // 14: proto.E2EService.NodeStatus:output_type -> proto.NodeStatusResponse
	12, // [12:15] is the sub-list for method output_type
	9,  // [9:12] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_internal_server_proto_service_proto_init() }
func file_internal_server_proto_service_proto_init() {
	if File_internal_server_proto_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_server_proto_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NodeDeployRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_server_proto_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NodeDeployResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_server_proto_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NodeListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_server_proto_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NodeListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_server_proto_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NodeStatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_server_proto_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NodeStatusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_server_proto_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Node); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_server_proto_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NodeDeployRequest_Beacon); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_server_proto_service_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NodeDeployRequest_Validator); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_internal_server_proto_service_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*NodeDeployRequest_Beacon_)(nil),
		(*NodeDeployRequest_Validator_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_server_proto_service_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_server_proto_service_proto_goTypes,
		DependencyIndexes: file_internal_server_proto_service_proto_depIdxs,
		EnumInfos:         file_internal_server_proto_service_proto_enumTypes,
		MessageInfos:      file_internal_server_proto_service_proto_msgTypes,
	}.Build()
	File_internal_server_proto_service_proto = out.File
	file_internal_server_proto_service_proto_rawDesc = nil
	file_internal_server_proto_service_proto_goTypes = nil
	file_internal_server_proto_service_proto_depIdxs = nil
}
